<template>
  <div class="page design">
    <hero-section
      title="Processes"
      subtitle="Living in complex social, economic, political, and ecological systems"
      image="https://source.unsplash.com/z6YCbf_El_A/1600x900"
      image-alt="Cascading waterfalls"
      color="secondary"
      size="is-large"
    />
    <section-intro
      title="Nothing is static. Everything is in process."
      subtitle="Process philosophy covers not just scientific intuitions and experiences, but can be used as a conceptual bridge to facilitate discussions among religion, philosophy, and science."
    >
      <p class="intro-paragraph">
        Process philosophy—also ontology of becoming, processism, or philosophy
        of organism—identifies metaphysical reality with change. In opposition
        to the classical model of change as illusory (as argued by Parmenides)
        or accidental (as argued by Aristotle), process philosophy regards
        change as the cornerstone of reality—the cornerstone of being thought of
        as becoming.
      </p>
      <a href="#processes" id="processes">
        <h1>Processes</h1>
      </a>
      <a href="#complex-systems" id="complex-systems">
        <h2>Living in complex social, economic, political, and ecological systems</h2>
      </a>
      <p>Since the time of Plato and Aristotle, some philosophers have posited true reality as “timeless”, based on permanent substances, while processes are denied or subordinated to timeless substances. If Socrates changes, becoming sick, Socrates is still the same (the substance of Socrates being the same), and change (his sickness) only glides over his substance: change is accidental, whereas the substance is essential. Therefore, classic ontology denies any full reality to change, which is conceived as only accidental and not essential. This classical ontology is what made knowledge and a theory of knowledge possible, as it was thought that a science of something in becoming was an impossible feat to achieve.</p>
      <p>Process philosophy covers not just scientific intuitions and experiences, but can be used as a conceptual bridge to facilitate discussions among religion, philosophy, and science.</p><a href="#twentieth-century" id="twentieth-century" class="css-vqbdhb"><h2 style="display: inline-block;">Twentieth century</h2></a>
      <p>In early twentieth century, the philosophy of mathematics was undertaken to develop mathematics as an airtight, axiomatic system in which every truth could be derived logically from a set of axioms. In the foundations of mathematics, this project is variously understood as logicism or as part of the formalist program of David Hilbert. Alfred North Whitehead and Bertrand Russell attempted to complete, or at least facilitate, this program with their seminal book Principia Mathematica, which purported to build a logically consistent set theory on which to found mathematics. After this, Whitehead extended his interest to natural science, which he held needed a deeper philosophical basis. He intuited that natural science was struggling to overcome a traditional ontology of timeless material substances that does not suit natural phenomena. According to Whitehead, material is more properly understood as ‘process’. In 1929, he produced the most famous work of process philosophy, Process and Reality, continuing the work begun by Hegel but describing a more complex and fluid dynamic ontology.</p>
      <p>Process thought describes truth as “movement” in and through substance (Hegelian truth), rather than substances as fixed concepts or “things” (Aristotelian truth). Since Whitehead, process thought is distinguished from Hegel in that it describes entities that arise or coalesce in becoming, rather than being simply dialectically determined from prior posited determinates. These entities are referred to as complexes of occasions of experience. It is also distinguished in being not necessarily conflictual or oppositional in operation. Process may be integrative, destructive or both together, allowing for aspects of interdependence, influence, and confluence, and addressing coherence in universal as well as particular developments, i.e., those aspects not befitting Hegel’s system. Additionally, instances of determinate occasions of experience, while always ephemeral, are nonetheless seen as important to define the type and continuity of those occasions of experience that flow from or relate to them.</p><a href="#whitehead’s-process-and-reality" id="whitehead’s-process-and-reality" class="css-vqbdhb"><h1 style="display: inline-block;">Whitehead’s Process and Reality</h1></a>
      <p>Alfred North Whitehead began teaching and writing on process and metaphysics when he joined Harvard University in 1924.</p>
      <p>In his book Science and the Modern World (1925), Whitehead noted that the human intuitions and experiences of science, aesthetics, ethics, and religion influence the worldview of a community, but that in the last several centuries science dominates Western culture. Whitehead sought a holistic, comprehensive cosmology that provides a systematic descriptive theory of the world which can be used for the diverse human intuitions gained through ethical, aesthetic, religious, and scientific experiences, and not just the scientific.</p>
      <p>Whitehead’s influences were not restricted to philosophers or physicists or mathematicians. He was influenced by the French philosopher Henri Bergson (1859–1941), whom he credits along with William James and John Dewey in the preface to Process and Reality.</p><a href="#process-metaphysics" id="process-metaphysics" class="css-vqbdhb"><h2 style="display: inline-block;">Process metaphysics</h2></a>
      <p>For Whitehead, metaphysics is about logical frameworks for the conduct of discussions of the character of the world. It is not directly and immediately about facts of nature, but only indirectly so, in that its task is to explicitly formulate the language and conceptual presuppositions that are used to describe the facts of nature. Whitehead thinks that discovery of previously unknown facts of nature can in principle call for reconstruction of metaphysics.</p>
      <p>The process metaphysics elaborated in Process and Reality posits an ontology which is based on the two kinds of existence of an entity, that of actual entity and that of abstract entity or abstraction, also called ‘object’.</p>
      <p>Actual entity is a term coined by Whitehead to refer to the entities that really exist in the natural world. For Whitehead, actual entities are spatiotemporally extended events or processes. An actual entity is how something is happening, and how its happening is related to other actual entities. The actually existing world is a multiplicity of actual entities overlapping one another.</p>
      <p>The ultimate abstract principle of actual existence for Whitehead is creativity. Creativity is a term coined by Whitehead to show a power in the world that allows the presence of an actual entity, a new actual entity, and multiple actual entities. Creativity is the principle of novelty. It is manifest in what can be called ‘singular causality’. This term may be contrasted with the term ‘nomic causality’. An example of singular causation is that I woke this morning because my alarm clock rang. An example of nomic causation is that alarm clocks generally wake people in the morning. Aristotle recognizes singular causality as efficient causality. For Whitehead, there are many contributory singular causes for an event. A further contributory singular cause of my being awoken by my alarm clock this morning was that I was lying asleep near it till it rang.</p>
      <p>An actual entity is a general philosophical term for an utterly determinate and completely concrete individual particular of the actually existing world or universe of changeable entities considered in terms of singular causality, about which categorical statements can be made. Whitehead’s most far-reaching and radical contribution to metaphysics is his invention of a better way of choosing the actual entities. Whitehead chooses a way of defining the actual entities that makes them all alike, qua actual entities, with a single exception.</p>
      <p>For example, for Aristotle, the actual entities were the substances, such as Socrates. Besides Aristotle’s ontology of substances, another example of an ontology that posits actual entities is in the monads of Leibniz, which are said to be ‘windowless’.</p><a href="#whitehead’s-actual-entities" id="whitehead’s-actual-entities" class="css-vqbdhb"><h2 style="display: inline-block;">Whitehead’s actual entities</h2></a>
      <p>For Whitehead’s ontology of processes as defining the world, the actual entities exist as the only fundamental elements of reality.</p>
      <p>The actual entities are of two kinds, temporal and atemporal.</p>
      <p>With one exception, all actual entities for Whitehead are temporal and are occasions of experience (which are not to be confused with consciousness). An entity that people commonly think of as a simple concrete object, or that Aristotle would think of as a substance, is, in this ontology, considered to be a temporally serial composite of indefinitely many overlapping occasions of experience. A human being is thus composed of indefinitely many occasions of experience.</p>
      <p>The one exceptional actual entity is at once both temporal and atemporal: God. He is objectively immortal, as well as being immanent in the world. He is objectified in each temporal actual entity; but He is not an eternal object.</p>
      <p>The occasions of experience are of four grades. The first grade comprises processes in a physical vacuum such as the propagation of an electromagnetic wave or gravitational influence across empty space. The occasions of experience of the second grade involve just inanimate matter; “matter” being the composite overlapping of occasions of experience from the previous grade. The occasions of experience of the third grade involve living organisms. Occasions of experience of the fourth grade involve experience in the mode of presentational immediacy, which means more or less what are often called the qualia of subjective experience. So far as we know, experience in the mode of presentational immediacy occurs in only more evolved animals. That some occasions of experience involve experience in the mode of presentational immediacy is the one and only reason why Whitehead makes the occasions of experience his actual entities; for the actual entities must be of the ultimately general kind. Consequently, it is inessential that an occasion of experience have an aspect in the mode of presentational immediacy; occasions of the grades one, two, and three, lack that aspect.</p>
      <p>There is no mind-matter duality in this ontology, because “mind” is simply seen as an abstraction from an occasion of experience which has also a material aspect, which is of course simply another abstraction from it; thus the mental aspect and the material aspect are abstractions from one and the same concrete occasion of experience. The brain is part of the body, both being abstractions of a kind known as persistent physical objects, neither being actual entities. Though not recognized by Aristotle, there is biological evidence, written about by Galen, that the human brain is an essential seat of human experience in the mode of presentational immediacy. We may say that the brain has a material and a mental aspect, all three being abstractions from their indefinitely many constitutive occasions of experience, which are actual entities.</p><a href="#time,-causality,-and-process" id="time,-causality,-and-process" class="css-vqbdhb"><h2 style="display: inline-block;">Time, causality, and process</h2></a>
      <p>Inherent in each actual entity is its respective dimension of time. Potentially, each Whiteheadean occasion of experience is causally consequential on every other occasion of experience that precedes it in time, and has as its causal consequences every other occasion of experience that follows it in time; thus it has been said that Whitehead’s occasions of experience are ‘all window’, in contrast to Leibniz’s ‘windowless’ monads. In time defined relative to it, each occasion of experience is causally influenced by prior occasions of experiences, and causally influences future occasions of experience. An occasion of experience consists of a process of prehending other occasions of experience, reacting to them. This is the process in process philosophy.</p>
      <p>Such process is never deterministic. Consequently, free will is essential and inherent to the universe.</p>
      <p>The causal outcomes obey the usual well-respected rule that the causes precede the effects in time. Some pairs of processes cannot be connected by cause-and-effect relations, and they are said to be spatially separated. This is in perfect agreement with the viewpoint of the Einstein theory of special relativity and with the Minkowski geometry of spacetime. It is clear that Whitehead respected these ideas, as may be seen for example in his 1919 book An Enquiry concerning the Principles of Natural Knowledge as well as in Process and Reality. Time in this view is relative to an inertial reference frame, different reference frames defining different versions of time.</p><a href="#atomicity" id="atomicity" class="css-vqbdhb"><h2 style="display: inline-block;">Atomicity</h2></a>
      <p>The actual entities, the occasions of experience, are logically atomic in the sense that an occasion of experience cannot be cut and separated into two other occasions of experience. This kind of logical atomicity is perfectly compatible with indefinitely many spatio-temporal overlaps of occasions of experience. One can explain this kind of atomicity by saying that an occasion of experience has an internal causal structure that could not be reproduced in each of the two complementary sections into which it might be cut. Nevertheless, an actual entity can completely contain each of indefinitely many other actual entities.</p>
      <p>Another aspect of the atomicity of occasions of experience is that they do not change. An actual entity is what it is. An occasion of experience can be described as a process of change, but it is itself unchangeable.</p>
      <p>The reader should bear in mind that the atomicity of the actual entities is of a simply logical or philosophical kind, thoroughly different in concept from the natural kind of atomicity that describes the atoms of physics and chemistry.</p><a href="#topology" id="topology" class="css-vqbdhb"><h2 style="display: inline-block;">Topology</h2></a>
      <p>Whitehead’s theory of extension was concerned with the spatio-temporal features of his occasions of experience. Fundamental to both Newtonian and to quantum theoretical mechanics is the concept of momentum. The measurement of a momentum requires a finite spatiotemporal extent. Because it has no finite spatiotemporal extent, a single point of Minkowski space cannot be an occasion of experience, but is an abstraction from an infinite set of overlapping or contained occasions of experience, as explained in Process and Reality. Though the occasions of experience are atomic, they are not necessarily separate in extension, spatiotemporally, from one another. Indefinitely many occasions of experience can overlap in Minkowski space.</p>
      <p>Nexus is a term coined by Whitehead to show the network actual entity from universe. In the universe of actual entities spread actual entity. Actual entities are clashing with each other and form other actual entities. The birth of an actual entity based on an actual entity, actual entities around him referred to as nexus.</p>
      <p>An example of a nexus of temporally overlapping occasions of experience is what Whitehead calls an enduring physical object, which corresponds closely with an Aristotelian substance. An enduring physical object has a temporally earliest and a temporally last member. Every member (apart from the earliest) of such a nexus is a causal consequence of the earliest member of the nexus, and every member (apart from the last) of such a nexus is a causal antecedent of the last member of the nexus. There are indefinitely many other causal antecedents and consequences of the enduring physical object, which overlap, but are not members, of the nexus. No member of the nexus is spatially separate from any other member. Within the nexus are indefinitely many continuous streams of overlapping nexūs, each stream including the earliest and the last member of the enduring physical object. Thus an enduring physical object, like an Aristotelian substance, undergoes changes and adventures during the course of its existence.</p>
      <p>In some contexts, especially in the theory of relativity in physics, the word ‘event’ refers to a single point in Minkowski or in Riemannian space-time. A point event is not a process in the sense of Whitehead’s metaphysics. Neither is a countable sequence or array of points. A Whiteheadian process is most importantly characterized by extension in space-time, marked by a continuum of uncountably many points in a Minkowski or a Riemannian space-time. The word ‘event’, indicating a Whiteheadian actual entity, is not being used in the sense of a point event.</p><a href="#whitehead’s-abstractions" id="whitehead’s-abstractions" class="css-vqbdhb"><h2 style="display: inline-block;">Whitehead’s abstractions</h2></a>
      <p>Whitehead’s abstractions are conceptual entities that are abstracted from or derived from and founded upon his actual entities. Abstractions are themselves not actual entities. They are the only entities that can be real but are not actual entities. This statement is one form of Whitehead’s ‘ontological principle’.</p>
      <p>An abstraction is a conceptual entity that refers to more than one single actual entity. Whitehead’s ontology refers to importantly structured collections of actual entities as nexuses of actual entities. Collection of actual entities into a nexus emphasizes some aspect of those entities, and that emphasis is an abstraction, because it means that some aspects of the actual entities are emphasized or dragged away from their actuality, while other aspects are de-emphasized or left out or left behind.</p>
      <p>‘Eternal object’ is a term coined by Whitehead. It is an abstraction, a possibility, or pure potential. It can be ingredient into some actual entity. It is a principle that can give a particular form to an actual entity.</p>
      <p>Whitehead admitted indefinitely many eternal objects. An example of an eternal object is a number, such as the number ‘two’. Whitehead held that eternal objects are abstractions of a very high degree of abstraction. Many abstractions, including eternal objects, are potential ingredients of processes.</p><a href="#relation-between-actual-entities-and-abstractions-stated-in-the-ontological-principle" id="relation-between-actual-entities-and-abstractions-stated-in-the-ontological-principle" class="css-vqbdhb"><h2 style="display: inline-block;">Relation between actual entities and abstractions stated in the ontological principle</h2></a>
      <p>For Whitehead, besides its temporal generation by the actual entities which are its contributory causes, a process may be considered as a concrescence of abstract ingredient eternal objects. God enters into every temporal actual entity.</p>
      <p>Whitehead’s ontological principle is that whatever reality pertains to an abstraction is derived from the actual entities upon which it is founded or of which it is comprised.</p><a href="#causation-and-concrescence-of-a-process" id="causation-and-concrescence-of-a-process" class="css-vqbdhb"><h2 style="display: inline-block;">Causation and concrescence of a process</h2></a>
      <p>Concrescence is a term coined by Whitehead to show the process of jointly forming an actual entity that was without form, but about to manifest itself into an entity Actual full (satisfaction) based on datums or for information on the universe. The process of forming an actual entity is the case based on the existing datums. Concretion process can be regarded as subjectification process.</p>
      <p>Datum is a term coined by Whitehead to show the different variants of information possessed by actual entity. In process philosophy, datum is obtained through the events of concrescence. Every actual entity has a variety of datum.</p>
      <ul>
        <li><a href="https://en.wikipedia.org/wiki/Process_philosophy" target="_blank">Wikipedia: Process philosophy</a></li>
      </ul>
    </section-intro>
  </div>
</template>

<script>
import HeroSection from '~/components/HeroSection'
import SectionIntro from '~/components/SectionIntro'

export default {
  name: 'ImaginePage',
  components: {
    HeroSection,
    SectionIntro
  }
}
</script>
